// This file is generated by scripts/generateGallery.js
const galleryImages = [
  "assets/images/gallery/bandet.png",
  "assets/images/gallery/bandet2.png",
  "assets/images/gallery/bandet3.png",
  "assets/images/gallery/bandet4.png",
  "assets/images/gallery/bandet5.png",
  "assets/images/gallery/bandet6.png"
];
