// This file is generated by scripts/generateGallery.js
const galleryImages = [
  "assets/images/gallery/411010457_759041982929307_3532161434539500038_n.jpg",
  "assets/images/gallery/bandet2.png",
  "assets/images/gallery/hela_bandet_valb_2024.jpg",
  "assets/images/gallery/malmö_vb_2024_18.jpg",
  "assets/images/gallery/malmö_vb_sexa_24_2.jpg",
  "assets/images/gallery/malmö_vb_sexa_24_5.jpg",
  "assets/images/gallery/mejeriet_lunds_kommun_7.jpeg",
  "assets/images/gallery/rockcasa_1.jpg",
  "assets/images/gallery/studio_vega_valborg_2023.jpg",
  "assets/images/gallery/studiovega_230318_270.jpg",
  "assets/images/gallery/studiovega_230318_296.jpg",
  "assets/images/gallery/studiovega_230318_323.jpg.jpg"
];
