const fs = require('fs');
const path = require('path');

const galleryDir = path.join(__dirname, '..', 'assets', 'images', 'gallery');
const outputFile = path.join(__dirname, '..', 'js', 'galleryData.js');

const extensions = ['.png', '.jpg', '.jpeg', '.gif', '.webp'];

const images = fs.readdirSync(galleryDir)
  .filter(file => extensions.includes(path.extname(file).toLowerCase()))
  .map(file => `assets/images/gallery/${file}`);

const content = `// This file is generated by scripts/generateGallery.js\n` +
                `const galleryImages = ${JSON.stringify(images, null, 2)};\n`;

fs.writeFileSync(outputFile, content);
console.log(`Generated ${outputFile} with ${images.length} images.`);
